### ISSUE TITLE
关于https://lab.imgb.space/post/yang-xx-yyds

### ISSUE THREAD

**Issue by XiaoYangTech** [GrassBlock1/Friend-of-mine#1]
首先我要声明一下，这个是确实是我干的！你分析的很好也很理智，但是我要澄清一点，用某scr软件当头像不代表我就是xxs，我可以给你看下我认证信息啊，不是xxs，现在我也有服务器了，本来我是在bing搜索我自己结果看到了这个帖子的，希望你删一下
作者: 草方块
链接: https://lab.imgb.space/post/yang-xx-yyds#%E4%B8%80%E4%BA%9B%E5%90%8E%E8%AF%9D
来源: Mare_Infinitus
著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。

**Comment by GrassBlock1** [comment]
你好！这两天一直在密切关注着你的动态，经过深思熟虑，我决定将相关文章删除，对你带来的损失实属抱歉。

**Comment by GrassBlock1** [comment]
>
